## Transformaciones necesarias para mostrar ubicacion geografica de localidades con conectividad por si o por no , discriminada por tipo de conectividad

In [1]:
import pandas as pd

Leo la tabla de localidades ya preparada por mi en EDA.py

In [5]:

loc_inter=pd.read_csv("data/16-Localcon_Internet.csv")

Leo la tabla de Información Censal del gobierno que contiene latitud y longitud por localidad

In [45]:
loc=pd.read_csv("data/localidades.csv")

Renombro columnas partidos y localidades a los fines de normalizar con ambas tablas

In [49]:
loc = loc.rename(columns={'departamento_nombre': 'Partido',})

In [48]:
loc = loc.rename(columns={'provincia_nombre': 'Provincia',})

In [75]:
loc = loc.rename(columns={'localidad_censal_nombre': 'Localidad',})

Borro columnas innecesarias

In [ ]:
loc.drop(['categoria',
        'fuente', 'id', 'localidad_censal_id',
        'municipio_id', 
       'provincia_id', 'provincia_nombre'])

In [51]:
loc.head(5)

,categoria,centroide_lat,centroide_lon,departamento_id,Partido,fuente,id,localidad_censal_id,localidad_censal_nombre,municipio_id,municipio_nombre,nombre,provincia_id,Provincia
0,Localidad simple,-35.033073,-60.280620,6021.0,Alberti,INDEC,6021010000,6021010,Alberti,60021.0,Alberti,ALBERTI,6,Buenos Aires
1,Localidad simple,-34.868119,-60.393971,6021.0,Alberti,INDEC,6021020000,6021020,Coronel Seguí,60021.0,Alberti,CORONEL SEGUI,6,Buenos Aires
2,Componente de localidad compuesta,-35.068014,-60.402597,6021.0,Alberti,INDEC,6021030000,6021030,Mechita,60021.0,Alberti,MECHITA,6,Buenos Aires
3,Localidad simple,-35.124382,-60.220061,6021.0,Alberti,INDEC,6021040000,6021040,Pla,60021.0,Alberti,PLA,6,Buenos Aires
4,Localidad simple,-35.109618,-60.070551,6021.0,Alberti,INDEC,6021050000,6021050,Villa Grisolía,60021.0,Alberti,VILLA GRISOLIA,6,Buenos Aires

In [23]:



loc_inter[loc_inter["Partido"]=="Alberti"]

,Unnamed: 0,Provincia,Partido,Localidad,ADSL,Cablemódem,Dial Up,Fibra óptica,4G,3G,Telefonía Fija,Wireless,Satelital
230,230,BUENOS AIRES,Alberti,Alberti (Est. Andrés Vaccarezza),SI,NO,SI,SI,SI,SI,SI,SI,NO
231,231,BUENOS AIRES,Alberti,Coronel Seguí,NO,NO,NO,NO,NO,NO,NO,NO,NO
232,232,BUENOS AIRES,Alberti,Mechita,SI,NO,NO,NO,SI,SI,NO,NO,NO
233,233,BUENOS AIRES,Alberti,Pla,NO,NO,NO,NO,NO,NO,SI,NO,NO
234,234,BUENOS AIRES,Alberti,Villa Grisolía (Est. Achupallas),NO,NO,NO,NO,SI,SI,NO,NO,NO
235,235,BUENOS AIRES,Alberti,Villa María,NO,NO,NO,NO,NO,NO,NO,NO,NO
311,311,BUENOS AIRES,Alberti,Villa Ortiz (Est. Coronel Mom),NO,NO,NO,NO,SI,SI,SI,NO,NO

Como contienen parentesis los nombre se los saco

In [24]:
# Definir una función para quitar el contenido entre paréntesis
def limpiar_localidad(localidad):
    return localidad.split('(')[0].strip()

# Aplicar la función a la columna 'Localidad'
loc_inter['Localidad'] = loc_inter['Localidad'].apply(limpiar_localidad)


# Utilizar str.replace para quitar el contenido entre paréntesis
loc_inter['Localidad'] = loc_inter['Localidad'].str.replace(r'\([^)]*\)', '').str.strip()

cambio los nombres de la provincia a formato mayuscula-minuscula

In [33]:
# Convertir cada palabra a formato "primera letra mayúscula y el resto minúscula"
loc_inter['Provincia'] = loc_inter['Provincia'].apply(lambda x: ' '.join(word.capitalize() for word in x.split()))

In [34]:
loc_inter

,Unnamed: 0,Provincia,Partido,Localidad,ADSL,Cablemódem,Dial Up,Fibra óptica,4G,3G,Telefonía Fija,Wireless,Satelital
0,0,Buenos Aires,9 de Julio,Alfredo Demarchi,SI,NO,NO,NO,SI,SI,SI,NO,NO
1,1,Buenos Aires,9 de Julio,Carlos María Naón,NO,NO,NO,NO,SI,SI,SI,NO,NO
2,2,Buenos Aires,9 de Julio,Dudignac,NO,NO,SI,NO,SI,SI,SI,SI,NO
3,3,Buenos Aires,9 de Julio,La Aurora,NO,NO,NO,NO,SI,NO,NO,NO,NO
4,4,Buenos Aires,9 de Julio,Manuel B. Gonnet,SI,NO,NO,SI,SI,SI,SI,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306,4306,Buenos Aires,Pilar,Pilar,SI,SI,SI,SI,SI,SI,SI,SI,SI
4307,4307,Buenos Aires,Pilar,Presidente Derqui,SI,SI,NO,SI,SI,SI,SI,SI,NO
4308,4308,Buenos Aires,Pilar,Roberto De Vicenzo,NO,NO,NO,NO,SI,SI,NO,NO,NO
4309,4309,Buenos Aires,Pilar,Santa Teresa,NO,NO,NO,NO,SI,SI,NO,NO,SI
4310,4310,Buenos Aires,Pilar,Tortuguitas,NO,NO,NO,SI,SI,SI,NO,SI,SI

In [42]:
loc.columns

Index(['categoria', 'centroide_lat', 'centroide_lon', 'departamento_id',
       'Partido', 'fuente', 'id', 'localidad_censal_id',
       'localidad_censal_nombre', 'municipio_id', 'municipio_nombre', 'nombre',
       'provincia_id', 'Provincia'],
      dtype='object')

Realizo el merge de loc_inter que es mi tabla y loc que es la tabla con las ubicaiones

In [76]:
# Juntar los DataFrames en base a las columnas 'Partido' y 'Localidad'

df_junto = pd.merge(loc_inter, loc, left_on=['Provincia','Partido', 'Localidad'], right_on=['Provincia','Partido', 'Localidad'], how='left')

Borro aquellos que no tuvieron match

In [81]:
df_junto.tail(2)

,Unnamed: 0,Provincia,Partido,Localidad,ADSL,Cablemódem,Dial Up,Fibra óptica,4G,3G,...,centroide_lat,centroide_lon,departamento_id,fuente,id,localidad_censal_id,municipio_id,municipio_nombre,nombre,provincia_id
4665,4309,Buenos Aires,Pilar,Santa Teresa,NO,NO,NO,NO,SI,SI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4666,4310,Buenos Aires,Pilar,Tortuguitas,NO,NO,NO,SI,SI,SI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_junto[['centroide_lon', 'departamento_id']].isna().sum()

In [82]:
# observo
loc[loc["Localidad"]=="Santa Teresa"]

,categoria,centroide_lat,centroide_lon,departamento_id,Partido,fuente,id,localidad_censal_id,Localidad,municipio_id,municipio_nombre,nombre,provincia_id,Provincia
2319,Localidad simple,-37.574934,-63.432886,42070.0,Guatraché,INDEC,42070050000,42070050,Santa Teresa,420343.0,Santa Teresa,SANTA TERESA,42,La Pampa
3489,Localidad simple,-33.438547,-60.791154,82028.0,Villa Constitución,INDEC,82028190000,82028190,Santa Teresa,822518.0,Santa Teresa,SANTA TERESA,82,Santa Fe

Grabo en un csv para usar en power BI

In [83]:
df_junto.to_csv("data/Localidades_internet.csv")